M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu24.04.1} date 2024-10-28T12:21:14+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-28T12:21:14+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X6.878Y-4.1732
X6.878Y-4.4882
M30
